version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-dezsys
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama


volumes:
  mysql_data:
  ollama_data: